flowchart LR

subgraph 0["index"]
1["index.js"]
2["addViewHistoryEvents_es2023.js"]
3["assert_es2023.js"]
4["BookSelect.es2023.js"]
5["BibleConstant.es2023.js"]
6["BibleConstantHelper.es2023.js"]
7["TPPageState.es2023.js"]
8["updateInstanceFromDict_es2023.js"]
9["BookSelectPopUp.es2023.js"]
A["BookSelectName.es2023.js"]
B["BookSelectChapter.es2023.js"]
C["FhlInfo.es2023.js"]
D["FhlInfoContent.es2023.js"]
E["ai_render_tools_es2023.js"]
F["ai_get_address_chapter.js"]
G["ai_get_address_paragraph.js"]
H["ParagraphData_es2023.js"]
I["loadAndDecompressJsonGzAsync.es2023.js"]
J["ai_get_limited_address_range.js"]
K["ai_parsing_gen_tp1_es2023.js"]
L["ai_get_address_tp.js"]
M["linq_es2023.js"]
N["ParsingCache_es2023.js"]
O["parsing_bind_word_and_wid_and_wu_es2023.js"]
P["splitStringByRegex.es2023.js"]
Q["matchGlobalWithCapture.es2023.js"]
R["Parsing_normalize_Address_es2023.js"]
S["ai_get_bcvw.js"]
T["ai_parsing_gen_exp.js"]
U["parsing_gen_prompt_parsing_table_es2023.js"]
V["parsing_gen_prompt_word_include_wid_es2023.js"]
W["ai_parsing_gen_tp1a_es2023.js"]
X["ai_parsing_gen_tp1b_es2023.js"]
Y["ai_parsing_get_data_async_es2023.js"]
Z["isRDLocation.es2023.js"]
10["ai_parsing_help_tp1_es2023.js"]
11["DialogHtml.es2023.js"]
12["ai_parsing_help_tp1a_es2023.js"]
13["ai_parsing_help_tp1b_es2023.js"]
14["ai_translations_gen_tp1_es2023.js"]
15["ai_translations_gen_tp1a_es2023.js"]
16["ai_translations_gen_tp1b_es2023.js"]
17["ai_translations_get_data_async_es2023.js"]
18["cvtAddrsToRef.es2023.js"]
19["ai_translations_help_tp1_es2023.js"]
1A["ai_translations_help_tp1a_es2023.js"]
1B["ai_translations_help_tp1b_es2023.js"]
1C["ai_translations_set_count_sec.js"]
1D["copy_text_to_clipboard_es2023.js"]
1E["comment_register_events_es2023.js"]
1F["FhlLecture.es2023.js"]
subgraph 1G["api"]
1H["qsb.js"]
1I["get_domain.js"]
3X["sc.js"]
end
1J["Bible_fhlwh_json.es2023.js"]
1K["BaseJson.es2023.js"]
1L["charHG.es2023.js"]
1M["getAjaxUrl.es2023.js"]
1N["getBookFunc.es2023.js"]
1O["lecture_get_data_async_es2023.js"]
subgraph 1P["lecture"]
1Q["FhlLecture_render_core.js"]
2D["FhlLecture_render_mode_common_es2023.js"]
end
1R["cvt_others.js"]
1S["AddParenthesesUnvNcv.js"]
1T["AddReferenceInCommentText.js"]
1U["deepCopy.js"]
1V["VerseRange.js"]
1W["ParsingReferenceDescription.js"]
1X["GetAddresses.js"]
1Y["SmartDescriptEndParsing.js"]
1Z["VerseRangeToString.js"]
20["attach_sn_text.js"]
21["cvt_other_text_like_foot.js"]
22["cvt_others_addFoot.js"]
23["ReferenceNcv.js"]
24["ReferenceOther.js"]
25["grouping_by_paragraph_for_dtexts_with_addr.js"]
26["grouping_by_paragraph.js"]
27["Hash_DAddress_es2023.js"]
28["queryFootsAsync.js"]
29["rtAsync.js"]
2A["render_dtexts.js"]
subgraph 2B["dtext"]
2C["dtexts_render.js"]
end
2E["add_sn_text.js"]
2F["ParsingPopUp.es2023.js"]
2G["dev_sbdag.es2023.js"]
2H["dev_stwcbhdic.es2023.js"]
2I["doSearch.es2023.js"]
2J["triggerGoEventWhenPageStateAddressChange.es2023.js"]
2K["queryDictionaryAndShowAtDialogAsync.es2023.js"]
2L["cvtDTextsToHtml.es2023.js"]
2M["queryReferenceAndShowAtDialogAsync.es2023.js"]
2T["prepare_dtexts_for_html.js"]
2U["splitReference.es2023.js"]
2V["ViewHistory.es2023.js"]
2W["DocumentCustomListenerState_es2023.js"]
2X["LeftWindowTool.es2023.js"]
2Y["gbText.es2023.js"]
2Z["testThenDo.es2023.js"]
30["SnDictOfCbol.es2023.js"]
31["cbolflow.es2023.js"]
32["splitBrOne.es2023.js"]
33["ISnDictionary.es2023.js"]
34["SnDictOfTwcb.es2023.js"]
35["twcbflow.es2023.js"]
36["splitBtw.es2023.js"]
37["Sd_cnt_json.es2023.js"]
38["SN_Act_Color.es2023.js"]
39["Sn_cnt_book_unv_json.es2023.js"]
3A["Sn_cnt_chap_unv_json.es2023.js"]
3B["ViewHistoryData_es2023.js"]
3C["comment_render_es2023.js"]
subgraph 3D["comments"]
3E["convertDocToDText.js"]
3F["parseComment.js"]
3G["buildTree.js"]
3H["detectTableBlocks.js"]
3I["normalizeTree.js"]
3J["preprocessCaseToLines.js"]
3K["replaceApiResult.js"]
3L["getJoTableOfKingdomOfJudah.js"]
3M["tokenizeLine.js"]
3N["render_comments_in_dtexts.js"]
end
3O["eachFitDo.es2023.js"]
3P["sc_api_es2023.js"]
3Q["ScResult_es2023.js"]
3R["parsing_render_async_es2023.js"]
3S["parsing_api_async_es2023.js"]
3T["parsing_render_bottom_table.es2023.js"]
3U["parsing_render_top.es2023.js"]
subgraph 3V["tsks"]
3W["renderTsk.js"]
3Y["cvt_ref_to_chinese.js"]
3Z["cvt_tsk_blocks_to_dtexts.js"]
40["parseTsk.js"]
end
41["FhlInfoTitle.es2023.js"]
42["DocEvent.es2023.js"]
43["coreInfoWindowShowHide.es2023.js"]
44["do_preach.es2023.js"]
45["FhlLeftWindow.es2023.js"]
46["Settings.es2023.js"]
47["FontSizeTool.es2023.js"]
48["FontSizeToolBase.es2023.js"]
49["GbSelect.es2023.js"]
4A["ImageTool.es2023.js"]
4B["MapTool.es2023.js"]
4C["RealTimePopUpSelect.es2023.js"]
4D["Show_mode.es2023.js"]
4E["SnSelect.es2023.js"]
4F["FhlMidWindow.es2023.js"]
4G["FhlMidBottomWindow.es2023.js"]
4H["FhlToolBar.es2023.js"]
4I["Help.es2023.js"]
4J["HelpingPopUp.es2023.js"]
4K["SearchTool.es2023.js"]
4L["WindowControl.es2023.js"]
4M["requestFullscreen.es2023.js"]
4N["windowAdjust.es2023.js"]
4O["hash_change_on_initial.js"]
4P["Hash_Changed.js"]
4Q["initPageStateFlow.es2023.js"]
4R["load_json_gz_Async.es2023.js"]
4S["Sd_same_json.es2023.js"]
4T["registerEvents_doc.es2023.js"]
4U["renderTsk.es2023.js"]
4V["Search_continue_search_es2023.js"]
4W["Search_create_dialog_search_result_es2023.js"]
4X["Search_DataForGroupUi_es2023.js"]
4Y["Search_initializePreSearchEventHandlersAsync_es2023.js"]
4Z["Search_pre_search_click_es2023.js"]
50["Search_UiOfGroupRender_es2023.js"]
51["SearchFlow_es2023.js"]
52["SnBranchRender.es2023.js"]
53["VersionSelect.es2023.js"]
end
subgraph 2N["https:"]
subgraph 2O[" "]
subgraph 2P["cdn.jsdelivr.net"]
subgraph 2Q["npm"]
subgraph 2R["markdown-it@14.1.0"]
2S["+esm"]
end
end
end
end
end
1-->2
1-->1H
1-->5
1-->6
1-->4
1-->31
1-->43
1-->18
1-->2L
1-->11
1-->44
1-->42
1-->C
1-->D
1-->41
1-->1F
1-->45
1-->4F
1-->4H
1-->2Y
1-->1N
1-->4O
1-->4P
1-->4Q
1-->33
1-->Z
1-->2X
1-->4R
1-->Q
1-->H
1-->2K
1-->2M
1-->4T
1-->4U
1-->4V
1-->4W
1-->4X
1-->4Y
1-->4Z
1-->50
1-->51
1-->38
1-->52
1-->30
1-->34
1-->32
1-->36
1-->2U
1-->P
1-->7
1-->2J
1-->35
1-->53
1-->2V
1-->4N
2-->3
2-->4
2-->42
2-->2W
2-->C
2-->1F
2-->2Z
2-->7
2-->2J
2-->2V
2-->3B
4-->3
4-->5
4-->6
4-->9
4-->C
4-->1F
4-->1N
4-->7
4-->2J
4-->2V
4-->3B
6-->5
6-->7
7-->5
7-->6
7-->8
8-->3
9-->A
A-->5
A-->B
A-->2Y
A-->1N
B-->5
B-->4
B-->9
B-->C
B-->1F
B-->2J
B-->2V
B-->3B
C-->D
C-->41
C-->1F
C-->2F
C-->7
D-->E
D-->3
D-->5
D-->6
D-->4
D-->1E
D-->3C
D-->3O
D-->C
D-->1F
D-->1M
D-->1N
D-->R
D-->3R
D-->3T
D-->3U
D-->N
D-->2K
D-->2M
D-->38
D-->2U
D-->7
D-->2J
D-->3W
D-->2V
E-->F
E-->G
E-->J
E-->K
E-->W
E-->X
E-->Y
E-->10
E-->12
E-->13
E-->14
E-->15
E-->16
E-->17
E-->19
E-->1A
E-->1B
E-->1C
E-->5
E-->6
E-->1D
E-->18
E-->Z
E-->H
E-->U
E-->7
F-->6
G-->6
G-->H
H-->I
J-->5
K-->L
K-->S
K-->T
K-->6
K-->U
K-->V
K-->N
L-->M
L-->N
N-->3
N-->O
N-->R
O-->P
P-->Q
R-->6
U-->S
V-->S
W-->6
W-->N
W-->7
X-->6
X-->N
X-->7
Y-->5
Y-->Z
Y-->N
Y-->7
10-->11
12-->11
13-->11
14-->L
14-->S
17-->6
17-->18
17-->Z
17-->M
17-->7
18-->6
19-->11
1A-->11
1B-->11
1C-->11
1C-->7
1E-->5
1E-->6
1E-->4
1E-->C
1E-->1F
1E-->1N
1E-->2K
1E-->2M
1E-->38
1E-->2U
1E-->7
1E-->2J
1E-->2V
1F-->1H
1F-->3
1F-->1J
1F-->5
1F-->6
1F-->4
1F-->1L
1F-->C
1F-->1M
1F-->1N
1F-->Z
1F-->1O
1F-->1Q
1F-->2F
1F-->2K
1F-->2M
1F-->29
1F-->37
1F-->38
1F-->39
1F-->3A
1F-->2U
1F-->2Z
1F-->7
1F-->2J
1F-->2V
1F-->3B
1H-->6
1H-->7
1H-->1I
1I-->Z
1J-->1K
1K-->I
1L-->P
1M-->3
1M-->5
1M-->6
1M-->Z
1N-->5
1N-->7
1O-->1H
1O-->1J
1O-->6
1O-->1M
1O-->Z
1O-->7
1Q-->1L
1Q-->1R
1Q-->25
1Q-->26
1Q-->27
1Q-->H
1Q-->28
1Q-->2A
1Q-->7
1Q-->2D
1R-->1S
1R-->1T
1R-->20
1R-->5
1R-->6
1R-->21
1R-->22
1R-->23
1R-->24
1R-->P
1R-->7
1S-->P
1T-->1U
1T-->P
1T-->7
1T-->1V
1V-->6
1V-->1W
1V-->1Z
1W-->3
1W-->6
1W-->1X
1W-->1Y
1W-->P
1X-->6
1X-->M
1Y-->6
1Y-->P
1Z-->6
20-->3
20-->P
21-->P
22-->P
23-->5
23-->P
25-->26
26-->27
28-->29
28-->P
28-->6
29-->6
29-->Z
29-->7
2A-->2C
2D-->2E
2D-->1L
2D-->7
2F-->2G
2F-->2H
2F-->2I
2F-->1M
2F-->7
2I-->5
2I-->4
2I-->C
2I-->1F
2I-->7
2I-->2J
2J-->3
2K-->2L
2K-->11
2K-->2M
2K-->30
2K-->34
2M-->1H
2M-->3
2M-->5
2M-->6
2M-->4
2M-->1R
2M-->18
2M-->2L
2M-->11
2M-->C
2M-->1F
2M-->2T
2M-->28
2M-->2U
2M-->7
2M-->2J
2M-->2V
2M-->2S
2T-->3
2T-->6
2U-->5
2U-->6
2U-->P
2V-->3
2V-->6
2V-->4
2V-->2W
2V-->C
2V-->1F
2V-->2X
2V-->2Z
2V-->7
2X-->2Y
2X-->7
2Y-->7
30-->31
30-->33
30-->Z
31-->32
31-->2U
32-->P
34-->33
34-->Z
34-->35
35-->32
35-->36
35-->2U
36-->Q
37-->1K
39-->1K
3A-->1K
3B-->2
3B-->2Z
3B-->7
3C-->3
3C-->5
3C-->1E
3C-->3E
3C-->3F
3C-->3N
3C-->3O
3C-->2Y
3C-->1M
3C-->1N
3C-->3P
3C-->3Q
3C-->P
3C-->7
3E-->P
3F-->3G
3F-->3H
3F-->3I
3F-->3J
3F-->3K
3F-->3M
3K-->3L
3P-->1M
3P-->3Q
3Q-->3
3Q-->5
3Q-->8
3R-->D
3R-->1M
3R-->3S
3R-->3T
3R-->3U
3R-->N
3R-->7
3S-->5
3S-->Z
3T-->1L
3T-->N
3U-->6
3U-->P
3W-->6
3W-->Z
3W-->2Z
3W-->3X
3W-->2C
3W-->7
3W-->3Y
3W-->3Z
3W-->40
3X-->6
3Y-->5
3Z-->5
40-->P
40-->6
41-->7
41-->2J
42-->5
42-->7
43-->7
44-->6
44-->7
45-->1F
45-->2Y
45-->2X
45-->46
45-->7
45-->2J
45-->2V
46-->47
46-->48
46-->49
46-->2Y
46-->4A
46-->2X
46-->4B
46-->4C
46-->4D
46-->4E
46-->7
47-->1F
47-->2Y
48-->1F
48-->2Y
48-->7
49-->A
49-->C
49-->41
49-->1F
49-->2Y
49-->7
49-->2J
4A-->1F
4A-->2Y
4A-->7
4A-->2J
4B-->1F
4B-->2Y
4B-->7
4B-->2J
4C-->C
4C-->D
4C-->1F
4C-->2Y
4C-->7
4C-->2J
4D-->1F
4D-->2Y
4D-->2J
4E-->1F
4E-->2Y
4E-->7
4E-->2J
4F-->1F
4F-->4G
4F-->7
4G-->7
4H-->4
4H-->4I
4H-->4K
4H-->7
4H-->4L
4I-->11
4I-->4J
4K-->2I
4K-->4G
4K-->2J
4L-->43
4L-->1F
4L-->4G
4L-->4M
4M-->4N
4O-->6
4O-->18
4O-->4P
4O-->2M
4O-->2U
4O-->7
4O-->2V
4O-->3B
4Q-->7
4Q-->2J
4R-->1J
4R-->37
4R-->4S
4R-->39
4R-->3A
4S-->1K
4T-->B
4T-->1N
4T-->7
4U-->6
4U-->2I
4U-->7
4W-->6
4Y-->2Z
4Z-->3
4Z-->4V
50-->6
50-->2Y
50-->4X
52-->Z
53-->2J
